

# GENERATED FILE - DO NOT EDIT DIRECTLY.
# Prompt: dfclean_remove.txt  Version: 1.0
# Generated by: Copilot (2026-03)
# Timestamp: 2026-02-28T13:10:00Z

"""
DataFrame column removal utilities.
"""

from __future__ import annotations
from typing import Any, Dict, List, Optional
import pandas as pd


def _validate_dataframe(df: pd.DataFrame) -> None:
    """Validate the input DataFrame.

    Args:
        df: The pandas DataFrame to validate.

    Raises:
        TypeError: If df is not a pandas DataFrame.
        ValueError: If df is empty.
    """
    if not isinstance(df, pd.DataFrame):
        raise TypeError("df must be a pandas DataFrame.")
    if df.empty:
        raise ValueError("df must not be empty.")


def _validate_df_config(df_config: Dict[str, Any]) -> None:
    """Validate the df_config dictionary.

    Args:
        df_config: Configuration dictionary for DataFrame cleaning.

    Raises:
        TypeError: If df_config is not a dict.
        ValueError: If df_config is empty.
    """
    if not isinstance(df_config, dict):
        raise TypeError("df_config must be a dictionary.")
    if not df_config:
        raise ValueError("df_config must not be empty.")


def _validate_inplace(inplace: bool) -> None:
    """Validate the inplace flag.

    Args:
        inplace: Boolean flag indicating in-place modification.

    Raises:
        TypeError: If inplace is not a bool.
    """
    if not isinstance(inplace, bool):
        raise TypeError("inplace must be a boolean.")


def _get_columns_to_remove(df_config: Dict[str, Any]) -> List[str]:
    """Extract and validate the list of columns to remove from df_config.

    Args:
        df_config: Configuration dictionary for DataFrame cleaning.

    Returns:
        A list of column names to remove. May be empty list.

    Raises:
        TypeError: If the 'remove' value is not a list of strings.
    """
    remove_value: Optional[Any] = df_config.get("remove")

    if remove_value is None:
        return []

    if not isinstance(remove_value, list):
        raise TypeError("df_config['remove'] must be a list of strings.")

    if not all(isinstance(col, str) for col in remove_value):
        raise TypeError("All values in df_config['remove'] must be strings.")

    return remove_value


def _drop_columns(
    df: pd.DataFrame,
    columns_to_remove: List[str],
    inplace: bool,
) -> pd.DataFrame:
    """Drop specified columns from the DataFrame.

    Args:
        df: The input DataFrame.
        columns_to_remove: List of column names to remove.
        inplace: Whether to modify the DataFrame in place.

    Returns:
        A DataFrame with the specified columns removed.
    """
    if not columns_to_remove:
        return df if inplace else df.copy()

    existing_columns = [col for col in columns_to_remove if col in df.columns]

    if inplace:
        df.drop(columns=existing_columns, inplace=True, errors="ignore")
        return df

    df_clean = df.drop(columns=existing_columns, errors="ignore")
    return df_clean


def process_removes(
    df: pd.DataFrame,
    df_config: Dict[str, Any],
    inplace: bool = False,
) -> pd.DataFrame:
    """Remove columns from a DataFrame based on a configuration dictionary.

    The function reads the optional ``"remove"`` key from ``df_config``.
    If present, it must be a list of strings representing column names.
    Any column in ``df`` whose name matches a value in this list is removed.
    It is not an error if a name in the list does not exist in ``df``.

    Args:
        df: The input pandas DataFrame. Must not be empty.
        df_config: Configuration dictionary. May optionally contain a
            ``"remove"`` key with a list of column names to remove.
        inplace: If True, modify ``df`` in place and return it.
            If False, operate on a copy and return the new DataFrame.

    Returns:
        A DataFrame with the specified columns removed.

    Raises:
        TypeError: If any argument does not match the expected type.
        ValueError: If ``df`` or ``df_config`` is empty.
    """
    _validate_dataframe(df)
    _validate_df_config(df_config)
    _validate_inplace(inplace)

    columns_to_remove = _get_columns_to_remove(df_config)
    df_clean = _drop_columns(df=df, columns_to_remove=columns_to_remove, inplace=inplace)
    return df_clean
